name: Speed Kernel Upstream

on:
  push:
    branches: 
      - speed-kernel-upstream
  
jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest  # Uses Ubuntu runner

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        path: shas-dream-oc-mt6768  # Your repo's directory name

    - name: Install Dependencies
      run: |
        cd ~/
        sudo apt-get update
        sudo apt-get install -y git make gcc bc flex bison libelf-dev build-essential zlib1g-dev libncurses5-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev libssl-dev
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar xzf Python-2.7.18.tgz
        cd Python-2.7.18
        ./configure
        make
        sudo make altinstall
        sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python2
        whereis python2.7
        whereis python2
    - name: Cache Proton Clang
      uses: actions/cache@v4
      with:
        path: $HOME/clang-15/aaa
        key: ${{ runner.os }}-proton-clang

    - name: Set Up Toolchain
      run: |
       if [ "${{ steps.cache-proton-clang.outputs.cache-hit }}" != "true" ]; then
         git clone https://gitlab.com/Jyotidwi/proton-clang.git -b clang-15 ~/clang-15/aaa
       else
         echo "Using cached Toolchain to reduce action time"
       fi

    - name: Build Kernel
      run: |
        cd shas-dream-oc-mt6768
        ./merlin.sh  # Replace with your actual build script

    - name: Upload ZIP Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel
        path: shas-dream-oc-mt6768/AnyKernel3-master/*.zip  # Path to generated ZIP
        retention-days: 90
        
